### PR TITLE
Add pipewire support ++

### PR DESCRIPTION
**Pull request by salkin-mada**
and removing tab indentation

### CODE REVIEW

**Comment by salkin-mada** [comment]
new naming style could be discussed - it just felt wrong to keep all those JackThis and JackThat in there.

**Comment by madskjeldgaard** [comment]
Whoop whoop

**Comment by salkin-mada** [comment]
Test this out. I think it's good to go.

**Comment by madskjeldgaard** [comment]
works perfectly

**Comment by salkin-mada** [comment]
okay now! :) double check. And goooo.

**Comment by salkin-mada** [comment]
ah wow . forgot to test this .. hahah

**Comment by salkin-mada** [comment]
there! introduced the *initClass, so we can have a lookup of all our supported linux plugins

**Pull request merged**
